fos_user:
    db_driver: orm # other valid values are 'mongodb' and 'couchdb'
    firewall_name: main
    user_class: AppBundle\Entity\User
    from_email:
        address: '%app.mailer.addr%'
        sender_name: '%app.mailer.name%'
