# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        CalendarCategory:
            class: App\Entity\CalendarCategory
            label: 'Kalender :: categorie'
            list:
                fields:
                    - { property: 'id', label: 'Id' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'sequence', label: 'Nr' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['sequence', 'ASC']
            form:
                fields:
                    - { property: 'title', label: 'Titel' }
                    #- { property: 'slug', label: 'Slug' }
                    - { property: 'description', label: 'Omschrijving' }
                    - { property: 'sequence', label: 'Volgorde' }
                    - { property: 'enabled', label: 'Actief' }
            show:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'description', label: 'Omschrijving', type: 'textarea' }
                    - { property: 'sequence', label: 'Volgorde' }
                    - { property: 'enabled', label: 'Actief' }
            edit:
                fields:
                    - { property: 'slug', label: 'Slug' }

        CalendarEvent:
            class: App\Entity\CalendarEvent
            label: 'Kalender :: event'
            list:
                fields:
                    - { property: 'draft', label: 'Draft', type: 'boolean' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'startTime', label: 'Van' }
                    - { property: 'trueEndTime', label: 'Tot', template: 'easy_admin/date_interval_template_datetime.html.twig', css_class: 'small' }
                    - { property: 'allDay', label: 'Hele dag', type: 'boolean' }
                    - { property: 'category', label: 'Categorie' }
                    - { property: 'location', label: 'Locatie' }
                    - { property: 'competition', label: 'Wedstrijd', type: 'boolean' }
                    - { property: 'cancelled', label: 'Annul.', type: 'boolean' }
                sort: ['startTime', 'ASC']
                dql_filter: 'entity.archived = false'
            form:
                fields:
                    - { type: 'group', label: 'Basisgegevens', icon: 'pencil', css_class: "col-xs-12 col-md-9" }
                    - { property: 'enabled', label: 'Actief', help: 'Eens actief/gepubliceerd kan je het event niet meer verwijderen.' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'startTime', label: 'Van' }
                    - { property: 'endTime', label: 'Tot' }
                    - { property: 'allDay', label: 'Hele dag', help: 'Of bij onbekend (start)uur' }
                    - { property: 'body', label: 'Tekst', type: 'fos_ckeditor', css_class: 'w-100', type_options: { config_name: 'standard' } }
                    - { property: 'cancelled', label: 'Geannuleerd' }
                    - { type: 'group', label: 'Opties', icon: 'cog', css_class: "col-xs-12 col-md-3" }
                    - { property: 'eventIsCompetition', label: 'Zwemwedstrijd' }
                    - { property: 'category', label: 'Categorie', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabledOrderBySequence'] } }
                    #- { property: 'description', label: 'Omschrijving', type: 'textarea' }
                    - { property: 'location', label: 'Locatie' }
                    - { property: 'url', label: 'Website' }
                    - { property: 'staticPage', label: 'Pagina' }
                    #- { property: 'imageFile', type: 'vich_image', label: 'Afbeelding', base_path: '%app.path.img.calendar%' }
                    - { property: 'documentFile', type: 'vich_file', label: 'Bijlage', base_path: '%app.path.doc.calendar%' }
            show:
                fields:
                    #- { type: 'group', label: 'Basisgegevens', icon: 'pencil', css_class: "col-xs-12 col-md-9" }
                    - { property: 'enabled', label: 'Actief' }
                    - { property: 'cancelled', label: 'Geannuleerd' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'trueStartTime', label: 'Van', type: 'datetime' }
                    - { property: 'calcEndTime', label: 'Tot', type: 'datetime' }
                    - { property: 'allDay', label: 'Hele dag' }
                    - { property: 'category', label: 'Categorie' }
                    - { property: 'body', label: 'Tekst', type: 'textarea', css_class: 'w-100'}
                    #- { type: 'group', label: 'Opties', icon: 'cog', css_class: "col-xs-12 col-md-3" }
                    - { property: 'location', label: 'Locatie' }
                    - { property: 'url', label: 'Website' }
                    - { property: 'competition', label: 'Zwemwedstrijd' }
                    #- { property: 'staticPage', label: 'Pagina' }
                    #- { property: 'imageFile', type: 'vich_image', label: 'Afbeelding', base_path: '%app.path.img.calendar%' }
                    #- { property: 'documentFile', type: 'vich_file', label: 'Bijlage', base_path: '%app.path.doc.calendar%' }
            edit:
                actions: ['delete']
            search:
                fields: ['title','startTime','endTime','location','category.title']
                # using an empty value to not apply any condition when searching
                # elements (this prevents inheriting the 'dql_filter' value defined in 'list')
                dql_filter: ''
