# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Competition:
            class: App\Entity\Competition
            label: 'Zwemwedstrijden'
            list:
                fields:
                    #- { property: 'id', label: 'Id' }
                    - { property: 'calendar.enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'calendar', label: 'Kalender event' }
                    - { property: 'calendar.location', label: 'Locatie' }
                    - { property: 'pool', label: 'Zwembad' }
                    - { property: 'restrictions', label: 'Limiet', type: 'boolean' }
                    - { property: 'calendar.cancelled', label: 'Annul.', type: 'boolean' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['calendar.startTime', 'DESC']
            edit:
                fields: ['-calendar']
            form:
                fields:
                    - { type: 'group', label: 'Basisgegevens', icon: 'pencil', css_class: "col-xs-12 col-md-9" }
                    - { property: 'calendar', label: 'Kalender event', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getUnassociatedCalendarEvents'] } }
                    - { property: 'teams', label: 'Groep', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] } }
                    - { property: 'teamCategories', label: 'Categorie', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] } }
                    #- { property: 'delegate', label: 'Afgevaardigde' }
                    #- { property: 'coaches', label: 'Trainers' }
                    #- { property: 'officials', label: 'Officials' }
                    - { type: 'group', label: 'Opties', icon: 'cog', css_class: "col-xs-12 col-md-3" }
                    - { property: 'restrictions', label: 'Limieten' }
                    - { property: 'multiDay', label: 'Overnachting' }
                    - { property: 'pool', label: 'Zwembad type', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] } }
            search:
                fields: ['calendar.title','calendar.startTime','calendar.endTime','calendar.location','teams.name','teamCategories.name','teams.abbr','teamCategories.abbr']

        CompetitionPool:
            class: App\Entity\CompetitionPool
            label: 'Zwemwedstrijd bad'
            list:
                fields:
                    - { property: 'id', label: 'Id' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'description', label: 'Omschrijving' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['title', 'ASC']
            form:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'description', label: 'Omschrijving', type: 'textarea' }
                    - { property: 'enabled', label: 'Actief' }

        CompetitionDocument:
            class: App\Entity\CompetitionDocument
            label: 'Zwemwedstrijd bijlage'
            list:
                fields:
                    - { property: 'id', label: 'Id' }
                    - { property: 'competition', label: 'Wedstrijd' }
                    - { property: 'category', label: 'Categorie' }
                    - { property: 'document', type: 'file', label: 'Document', base_path: '%app.path.doc.competition%' }
                    #- { property: 'url', label: 'Url' }
                    - { property: 'description', label: 'Omschrijving' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['id', 'ASC']
            form:
                fields:
                    - { property: 'competition', label: 'Wedstrijd', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getUnarchivedCompetitionEvents'] } }
                    - { property: 'category', label: 'Categorie', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabledOrderBySequence'] } }
                    - { property: 'documentFile', type: 'vich_file', label: 'Document', base_path: '%app.path.doc.competition%' }
                    - { property: 'url', label: 'Externe url', help: 'In plaats van een document up te loaden kan je een extern document linken. Wel de volledige url geven. En een bijlage heeft voorrang op een externe link.' }
                    - { property: 'description', label: 'Bijschrift', help: 'Extra omschrijving bij meerdere documenten van dezelfde categorie, bv. {categorie} za voormiddag' }
            edit:
                actions: ['delete']
            search:
                fields: ['category.title','competition.teamCategories.name','competition.teamCategories.abbr','competition.teams.name','competition.teams.abbr','competition.calendar.location','competition.calendar.startTime','competition.calendar.endTime','competition.calendar.title']

        CompetitionDocumentCategory:
            class: App\Entity\CompetitionDocumentCategory
            label: 'Zwemwedstrijd bijlage categorie'
            list:
                fields:
                    - { property: 'sequence', label: 'Nr' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['sequence', 'ASC']
            form:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'description', label: 'Omschrijving', type: 'textarea' }
                    - { property: 'sequence', label: 'Volgorde' }
                    - { property: 'enabled', label: 'Actief' }
