# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Competition:
            class: App\Entity\Competition
            label: 'Zwemwedstrijd'
            list:
                fields:
                    #- { property: 'id', label: 'id' }
                    - { property: 'calendar', label: 'Kalender event', type: 'text' }
                    - { property: 'calendar.location', label: 'Locatie' }
                    - { property: 'organization', label: 'Org.' }
                    - { property: 'pool', label: 'Bad', type: 'text' }
                    - { property: 'enrol', label: 'Inschr.', type: 'boolean' }
                    - { property: 'enrolBefore', label: 'Tot', template: 'easy_admin/localizeddate_medium.html.twig' }
                    - { property: 'competitionParts', label: 'Delen' }
                    - { property: 'restrictions', label: 'Limiet', type: 'boolean' }
                    - { property: 'registrationid', label: 'Vergunning', type: 'boolean' }
                sort: ['calendar.startTime', 'ASC']
                dql_filter: 'calendar.archived = false AND calendar.cancelled = false'
            form:
                fields:
                    - { type: 'group', label: 'Basisgegevens', icon: 'pencil', css_class: "col-xs-12 col-md-9" }
                    - { property: 'calendar', label: 'Kalender event', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getUnassociatedCalendarEvents'] } }
                    - { property: 'calendar.title', label: 'Titel', type: 'text' }
                    - { property: 'calendar.startTime', label: 'Van', type: 'datetime', type_options: { disabled: true }, template: 'easy_admin/trans.html.twig' }
                    - { property: 'calendar.trueEndTime', label: 'Tot', type: 'datetime', type_options: { disabled: true }, template: 'easy_admin/trans.html.twig' }


                    - { property: 'calendar.body', label: 'Tekst', type: 'fos_ckeditor', css_class: 'w-100', type_options: { config_name: 'standard' } }
                    #- { property: 'delegate', label: 'Afgevaardigde' }
                    #- { property: 'coaches', label: 'Trainers' }
                    #- { property: 'officials', label: 'Officials' }
                    - { type: 'group', label: 'Opties', icon: 'cog', css_class: "col-xs-12 col-md-3" }
                    - { property: 'pool', label: 'Zwembad type', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] } }
                    - { property: 'organization', label: 'Organisatie', type_options: { attr: { maxlength: 20 }, required: true } }
                    - { property: 'calendar.location', label: 'Locatie', type: 'text', type_options: { required: true } }
                    - { property: 'calendar.url', label: 'Website', type: 'text' }
                    - { property: 'overnight', label: 'Met overnachting' }
                    - { type: 'group', label: 'Filter leden', icon: 'filter', css_class: "col-xs-12 col-md-9" }
                    - { property: 'teams', label: 'Groep', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] }, by_reference: false, css_class: 'mb-4', help: 'Selecteer de trainingsgroep die deelneemt aan de wedstrijd. Enkel geselecteerde groepen kunnen inschrijven.' }
                    - { property: 'noregistrationid', label: 'Niet-vergunningshouders', type: 'checkbox' }
                    - { property: 'restrictions', label: 'Limieten' }
                    - { property: 'similarGenderAgeLimits', label: 'Zelfde leeftijden voor jongens/meisjes', help: 'Geef bij gelijke leeftijdslimieten enkel de jongens in. Geen geboortejaren maar leeftijden invullen. Het geboortejaar wordt nadien bepaald met de datum van de wedstrijd.' }
                    - { property: 'maleAgeMin', label: 'Jongens vanaf', css_class: "col-xs-12 col-md-3", help: 'leeg is geen minimale leeftijd', type_options: { attr: { min: 5, max: 25 } } }
                    - { property: 'maleAgeMax', label: 'Jongens tot en met', css_class: "col-xs-12 col-md-3", help: 'leeg is geen maximale leeftijd', type_options: { attr: { min: 9, max: 99 } } }
                    - { property: 'femaleAgeMin', label: 'Meisjes vanaf', css_class: "col-xs-12 col-md-3", help: 'leeg is geen minimale leeftijd', type_options: { attr: { min: 5, max: 25 } } }
                    - { property: 'femaleAgeMax', label: 'Meisjes tot en met', css_class: "col-xs-12 col-md-3", help: 'leeg is geen maximale leeftijd', type_options: { attr: { min: 9, max: 99 } } }
                    - { type: 'group', label: 'Inschrijvingen (dagdelen)', icon: 'check', css_class: "col-xs-12 col-md-9" }
                    - { property: 'enrolBeforeDays', label: 'Inschrijftermijn (dagen voor aanvang wedstrijd)', css_class: "", type_options: { attr: { min: 7, max: 30 } } }
                    - { property: 'competitionParts', label: 'Dagdelen', type_options: { multiple: true, disabled: true }, template: 'easy_admin/trans.html.twig' }
                    - { property: 'updatePartList', label: 'Ontbrekende dagdelen aanmaken', type: 'checkbox', help: 'Overbodige dagdelen kan je manueel verwijderen zolang de status draft is.', css_class: 'mt-4' }
                    - { property: 'partList', label: 'Dagdeel', type: 'choice', type_options: { multiple: true, choices: {'morning':0, 'afternoon':1, 'evening':2}  } }

            new:
                fields: ['-calendar.title','-calendar.body','-calendar.startTime','-calendar.trueEndTime','-calendar.location','-calendar.url']
            edit:
                fields: ['-calendar']
            search:
                fields: ['calendar.title','calendar.startTime','calendar.endTime','calendar.location','teams.name','teams.abbr']
                # using an empty value to not apply any condition when searching
                # elements (this prevents inheriting the 'dql_filter' value defined in 'list')
                dql_filter: ''

        CompetitionPool:
            class: App\Entity\CompetitionPool
            label: 'Zwemwedstrijd bad'
            list:
                fields:
                    - { property: 'id', label: 'Id' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'description', label: 'Omschrijving' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['title', 'ASC']
            form:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'description', label: 'Omschrijving', type: 'textarea' }
                    - { property: 'enabled', label: 'Actief' }

        CompetitionDocument:
            class: App\Entity\CompetitionDocument
            label: 'Zwemwedstrijd bijlage'
            list:
                fields:
                    - { property: 'competition', label: 'Wedstrijd' }
                    - { property: 'category', label: 'Categorie' }
                    - { property: 'document', type: 'file', label: 'Document', base_path: '%app.path.doc.competition%' }
                    - { property: 'description', label: 'Omschrijving' }
                sort: ['competition', 'DESC']
            form:
                fields:
                    - { property: 'competition', label: 'Wedstrijd', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getUnarchivedCompetitionEvents'] } }
                    - { property: 'category', label: 'Categorie', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabledOrderBySequence'] } }
                    - { property: 'documentFile', type: 'vich_file', label: 'Document', base_path: '%app.path.doc.competition%' }
                    - { property: 'url', label: 'Externe url', help: 'In plaats van een document up te loaden kan je een extern document linken. Wel de volledige url geven. En een bijlage heeft voorrang op een externe link.' }
                    - { property: 'description', label: 'Bijschrift', help: 'Extra omschrijving bij meerdere documenten van dezelfde categorie, bv. {categorie} za voormiddag' }
            edit:
                actions: ['delete']
            search:
                fields: ['category.title','competition.teams.name','competition.teams.abbr','competition.calendar.location','competition.calendar.startTime','competition.calendar.endTime','competition.calendar.title']

        CompetitionDocumentCategory:
            class: App\Entity\CompetitionDocumentCategory
            label: 'Zwemwedstrijd bijlage categorie'
            list:
                fields:
                    - { property: 'sequence', label: 'Nr' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'title', label: 'Titel' }
                    - { property: 'slug', label: 'Slug' }
                    - { property: 'autoCleanup', label: 'Automatisch verwijderen', type: 'boolean' }
                    - { property: 'cleanupDelay', label: 'Timeout (dagen)' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['sequence', 'ASC']
            form:
                fields:
                    - { property: 'title', label: 'Titel' }
                    - { property: 'description', label: 'Omschrijving', type: 'textarea' }
                    - { property: 'sequence', label: 'Volgorde' }
                    - { property: 'enabled', label: 'Actief' }
                    - { property: 'autoCleanup', label: 'Automatisch verwijderen' }
                    - { property: 'cleanupDelay', label: 'Verwijder timeout (dagen)' }


        CompetitionPartDraft:
            class: App\Entity\CompetitionPart
            label: 'Draft dagdelen'
            list:
                fields:
                    - { property: 'competition.name', label: 'Wedstrijd', type: 'text' }
                    - { property: 'competition.organization', label: 'Org.', type: 'text' }
                    - { property: 'daypart', label: 'Datum', template: 'easy_admin/localizeddate_full.html.twig' }
                    - { property: 'partname', label: 'Dagdeel', template: 'easy_admin/trans.html.twig' }
                sort: ['daypart', 'ASC']
                dql_filter: 'entity.enabledAt is null'
                actions: ['-new','-edit','delete']
                batch_actions: ['enable']

        CompetitionPartActive:
            class: App\Entity\CompetitionPart
            label: 'Actieve dagdelen'
            list:
                fields:
                    - { property: 'competition.name', label: 'Wedstrijd', type: 'text' }
                    - { property: 'competition.organization', label: 'Org.', type: 'text' }
                    - { property: 'daypart', label: 'Datum', template: 'easy_admin/localizeddate_full.html.twig' }
                    - { property: 'partname', label: 'Dagdeel', template: 'easy_admin/trans.html.twig' }
                    - { property: 'cancelled', label: 'Geannul.', type: 'boolean' }
                    - { property: 'enrolments', label: 'Inschrijvingen' }
                sort: ['daypart', 'ASC']
                dql_filter: 'entity.archived = false AND entity.enabledAt is not null'
                actions: ['-new','-edit','-delete']
                #batch_actions: ['enable']

        CompetitionEnrolments:
            class: App\Entity\CompetitionEnrolment
            label: 'Inschrijvingen'
            list:
                fields:
                    - { property: 'competitionPart.competition.name', label: 'Wedstrijd', type: 'text' }
                    - { property: 'competitionPart.daypart', label: 'Datum', template: 'easy_admin/localizeddate_full.html.twig' }
                    - { property: 'competitionPart.partname', label: 'Dagdeel', template: 'easy_admin/trans.html.twig' }
                    - { property: 'competitor', label: 'Naam', type: 'text' }
                    - { property: 'competitor.team', label: 'Groep', type: 'text' }
                    - { property: 'enabled', label: 'Toeg.', type: 'boolean' }
                    - { property: 'qualified', label: 'Limiet', type: 'boolean' }
                    - { property: 'isEnrolled', label: 'Ingeschreven', type: 'boolean' }
                    - { property: 'enrolledAt', label: 'Op' }
                sort: ['competitionPart.daypart', 'ASC']
                dql_filter: 'entity.filtered = true'
                #dql_filter: 'entity.filtered = true AND entity.restrictions = true'
                actions: ['-new','-edit','-delete']
                batch_actions: ['qualified','unqualified']
                max_results: 50
            search:
                fields: ['competitionPart.competition.calendar.title','competitionPart.daypart','competitionPart.competition.organization','competitionPart.competition.calendar.location','competitor.firstname','competitor.lastname']
                #dql_filter: 'entity.filtered = true'
                dql_filter: ''
