# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Member:
            class: App\Entity\Member
            label: 'Leden'
            list:
                fields:
                    - { property: 'memberId', label: 'Lidnr' }
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'team', label: 'Zwemgroep', type: 'text' }
                    - { property: 'user', label: 'Beheerder' }
                    - { property: 'registrationId', label: 'Licentie' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                sort: ['memberId', 'ASC']
                batch_actions: ['enable','disable']
                actions: ['-new']
            form:
                fields:
                    - { property: 'memberId', label: 'Lid nummer', help: 'Lid nummer van Assist Online (uniek!).'}
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'gender', label: 'Geslacht', type: 'choice', type_options: { choices: {'Man': 'M', 'Vrouw': 'F'} } }
                    - { property: 'birthdate', label: 'Geboortedatum', type: 'birthday' }
                    - { property: 'address', label: 'Address' }
                    - { property: 'memberSince', label: 'Lid sinds' }
                    - { property: 'registrationId', label: 'Licentienummer' }
                    - { property: 'team', label: 'Zwemt bij', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] }  }
                    - { property: 'grouping', label: 'Tags' }
                    - { property: 'user', label: 'Beheerder', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getAdultUsers'] }  }
                    - { property: 'enabled', label: 'Actief' }
            search:
                fields: ['firstname','lastname','team.name','team.abbr','user.lastname','user.firstname','registrationId']
                dql_filter: ''
            show:
                fields:
                    - { property: 'memberId', label: 'Lid nummer (Assist)'}
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'gender', label: 'Geslacht' }
                    - { property: 'birthdate', label: 'Geboortedatum', type: 'birthday' }
                    - { property: 'address', label: 'Address' }
                    - { property: 'memberSince', label: 'Lid sinds' }
                    - { property: 'registrationId', label: 'Licentienummer' }
                    - { property: 'team', label: 'Zwemt bij'  }
                    - { property: 'grouping', label: 'Tags' }
                    - { property: 'user', label: 'Beheerder'  }
                    - { property: 'enabled', label: 'Actief' }

        MemberAddress:
            class: App\Entity\MemberAddress
            label: 'Adres'
            list:
                fields:
                    - { property: 'street', label: 'Straat en nummer' }
                    - { property: 'zip', label: 'Postcode' }
                    - { property: 'town', label: 'Plaats' }
                    - { property: 'nation', label: 'Land' }
                    - { property: 'members', label: 'Leden' }
                sort: ['zip', 'ASC']
            form:
                fields:
                    #- { property: 'member', label: 'Leden' }
                    - { property: 'street', label: 'Straat en nr' }
                    - { property: 'zip', label: 'Postcode' }
                    - { property: 'town', label: 'Plaats' }
                    - { property: 'nation', label: 'Land', type: 'country', with_flag: true }
                    - { property: 'members', label: 'Leden' }
                    - { property: 'user', label: 'Eigenaar' }


        MemberGrouping:
            class: App\Entity\MemberGrouping
            label: 'Groep'
            list:
                fields:
                    - { property: 'name', label: 'Naam' }
                    - { property: 'category', label: 'Categorie', template: 'easy_admin/trans.html.twig' }
                    - { property: 'description', label: 'Omschrijving' }
                    - { property: 'members', label: 'Leden' }
                    - { property: 'sequence', label: 'Volgorde' }
                    - { property: 'public', label: 'Zoekbaar', type: 'boolean' }
                sort: ['sequence', 'ASC']
            form:
                fields:
                    - { property: 'name', label: 'Naam/functie' }
                    - { property: 'description', label: 'Korte omschrijving', type: 'textarea' }
                    - { property: 'category', label: 'Categorie', type: 'choice', type_options: { multiple: false, choices: {'GROUPING_BOARD':'GROUPING_BOARD','GROUPING_DAILY_OPERATIONS':'GROUPING_DAILY_OPERATIONS','GROUPING_COACHES':'GROUPING_COACHES','GROUPING_OFFICIALS':'GROUPING_OFFICIALS'}, required: true  } }
                    - { property: 'sequence', label: 'Volgorde' }
                    - { property: 'public', label: 'Publiek zoekbaar' }
