# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Member:
            class: App\Entity\Member
            label: 'Leden'
            list:
                fields:
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'team', label: 'Zwemgroep' }
                    - { property: 'user', label: 'Beheerder' }
                sort: ['firstname', 'ASC']
            form:
                fields:
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'gender', label: 'Geslacht', type: 'choice', type_options: { choices: {'Man': 'M', 'Vrouw': 'F'} } }
                    - { property: 'birthdate', label: 'Geboortedatum', type: 'birthday' }
                    - { property: 'address', label: 'Address' }
                    - { property: 'memberSince', label: 'Lid sinds' }
                    - { property: 'registrationId', label: 'Licentienummer' }
                    - { property: 'team', label: 'Zwemt bij', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] }  }
                    - { property: 'grouping', label: 'Groepen', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getMemberGrouping'] }  }
                    - { property: 'user', label: 'Beheerder', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'] }  }
                    - { property: 'enabled', label: 'Actief' }

        MemberAddress:
            class: App\Entity\MemberAddress
            label: 'Adres'
            list:
                fields:
                    - { property: 'street', label: 'Straat en nummer' }
                    - { property: 'zip', label: 'Postcode' }
                    - { property: 'town', label: 'Plaats' }
                    - { property: 'nation', label: 'Land' }
                    - { property: 'members', label: 'Leden' }
                sort: ['zip', 'ASC']
            form:
                fields:
                    #- { property: 'member', label: 'Leden' }
                    - { property: 'street', label: 'Straat en nr' }
                    - { property: 'zip', label: 'Postcode' }
                    - { property: 'town', label: 'Plaats' }
                    - { property: 'nation', label: 'Land', type: 'country', with_flag: true }
                    - { property: 'members', label: 'Leden' }
                    - { property: 'user', label: 'Eigenaar' }


        MemberGrouping:
            class: App\Entity\MemberGrouping
            label: 'Groep'
            list:
                fields:
                    - { property: 'fullname', label: 'Volledige naam' }
                    - { property: 'description', label: 'Omschrijving' }
                    - { property: 'members', label: 'Leden' }
                    - { property: 'sequence', label: 'Volgorde' }
                    - { property: 'public', label: 'Zoekbaar', type: 'boolean' }
                    - { property: 'slug', label: 'Slug' }
                sort: ['sequence', 'ASC']
            form:
                fields:
                    - { property: 'name', label: 'Naam/functie' }
                    - { property: 'description', label: 'Korte omschrijving', type: 'textarea' }
                    - { property: 'sequence', label: 'Volgorde' }
                    - { property: 'public', label: 'Publiek zoekbaar' }
