# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        Tryout:
            class: App\Entity\Tryout
            label: 'Contactformulier'
            list:
                fields:
                    #- { property: 'id', label: 'Id' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'startTime', label: 'Wanneer' }
                    - { property: 'duration', label: 'Duur' }
                    - { property: 'enrolments', label: 'Inschrijvingen' }
                    - { property: 'maxEnrolments', label: 'Max' }
                    - { property: 'publishAt', label: 'Gepubliceerd op' }
                    - { property: 'updatedAt', label: 'Laatst aangepast' }
                sort: ['startTime', 'ASC']
            form:
                fields:
                    - { property: 'startTime', label: 'Wanneer' }
                    - { property: 'duration', label: 'Duur' }
                    - { property: 'maxEnrolments', label: 'Max inschrijvingen' }
                    - { property: 'enabled', label: 'Actief' }
                    - { property: 'publishAt', label: 'Publiceren vanaf' }
            edit:
                actions: ['delete']
