# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        User:
            class: App\Entity\User
            label: 'Gebruikers'
            list:
                fields:
                    - { property: 'id', label: 'Id' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'verified', label: 'Geverifieerd', type: 'boolean' }
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'isActive', label: 'Online', type: 'boolean' }
                    - { property: 'lastActiveAt', label: 'Laatst online' }
                    - { property: 'roles' }
                    - { property: 'members', label: 'Leden' }
                sort: ['id', 'ASC']
                actions: ['show']
            form:
                fields:
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'mobilePhone', label: 'Mobiel nr' }
                    - { property: 'enabled', label: 'Actief' }
                    - { property: 'verified', label: 'Geverifieerd' }
                    - { property: 'members', label: 'Ledenbeheer' }
                    - { property: 'roles', label: 'Toegangsrechten', type: 'choice', type_options: { multiple: true, choices: { 'Lid':'ROLE_USER', '- Gebruiker (volw/voogd)': 'ROLE_ADULT', 'Trainer': 'ROLE_COACH','Bestuurslid':'ROLE_BOARD', 'Manager':'ROLE_MANAGER', 'Beheerder': '- ROLE_ADMIN', '-- Superbeheerder': 'ROLE_SUPERADMIN' } } }
            show:
                fields:
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'mobilePhone', label: 'Mobiel nr' }
                    - { property: 'verified', label: 'Geverifieerd' }
                    - { property: 'enabled', label: 'Toegang' }
                    - { property: 'roles', label: 'Toegangsrechten' }
                    - { property: 'isActive', label: 'Online', type: 'boolean' }
                    - { property: 'lastActiveAt', label: 'Laatst online' }
                    - { property: 'members', label: 'Ledenbeheer' }
