# This file sets the configuration of the 'Category' entity.
#
# NOTE: this demo application splits the backend configuration into several
# small files for educational purposes. In your application you can put the
# entire backend configuration in just one file.
#
# The configuration options are explained in detail in the bundle documentation,
# which is published at https://github.com/javiereguiluz/EasyAdminBundle
easy_admin:
    entities:
        User:
            class: App\Entity\User
            label: 'Gebruikers'
            list:
                fields:
                    #- { property: 'id', label: 'Id' }
                    - { property: 'enabled', label: 'Actief', type: 'boolean' }
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'members', label: 'Leden' }
                    - { property: 'verified', label: 'Geverifieerd', type: 'boolean' }
                    - { property: 'isActive', label: 'Online', type: 'boolean' }
                    - { property: 'lastActiveAt', label: 'Laatst online' }
                    - { property: 'isAdmin', label: 'Backend', type: 'boolean' }
                sort: ['id', 'ASC']
                actions: ['show']
                batch_actions: ['enable','disable','verify','reinvite']
            form:
                fields:
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'mobilePhone', label: 'Mobiel nr' }
                    #- { property: 'verified', label: 'Geverifieerd' }
                    - { property: 'members', label: 'Ledenbeheer', type_options: { query_builder: ['App\Repository\EasyAdminRepository','getEnabled'], by_reference: false } }
                    - { property: 'roles', label: 'Toegangsrechten', type: 'choice', type_options: { multiple: true, choices: { 'Lid':'ROLE_USER', 'Trainer': 'ROLE_COACH', 'Bestuurslid': 'ROLE_BOARD', 'Beheerder': 'ROLE_ADMIN', '- Superbeheerder': 'ROLE_SUPER_ADMIN' } } }
                    - { property: 'enabled', label: 'Actief' }
            show:
                fields:
                    - { property: 'firstname', label: 'Voornaam' }
                    - { property: 'lastname', label: 'Achternaam' }
                    - { property: 'email', label: 'Email' }
                    - { property: 'mobilePhone', label: 'Mobiel nr' }
                    - { property: 'verified', label: 'Geverifieerd' }
                    - { property: 'enabled', label: 'Toegang' }
                    - { property: 'roles', label: 'Toegangsrechten' }
                    - { property: 'isActive', label: 'Online', type: 'boolean' }
                    - { property: 'lastActiveAt', label: 'Laatst online' }
                    - { property: 'members', label: 'Ledenbeheer' }
