# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'nl'
    app_locales: nl|en
    timezone: 'Europe/Brussels'
    app.mailer.addr: 'webmaster@hozt.be'
    app.mailer.name: 'Webmaster HoZT'
    app.about.abbr: 'HoZT'
    app.about.name: 'Hoogstratens Zwem Team'
    app.about.org.name: '%app.about.name% vzw'
    app.about.org.number: 'BE0644916871'
    app.about.bank_account: 'BE88 0689 0449 7341'
    app.defaults.blogPost.items_home: 3
    app.defaults.blogPost.items_page: 10
    app.defaults.blogCategory.id: 1
    app.defaults.calendarCategory.id: 3
    app.defaults.competitionPool.id: 1
    app.defaults.sponsorCategory.id: 1
    app.path.blogPost_documents: /uploads/files/blog
    app.path.blogPost_images: /uploads/images/blog
    app.path.calendar_documents: /uploads/files/calendar
    app.path.calendar_images: /uploads/images/calendar
    app.path.carousel_images: /uploads/images/carousel
    app.path.competition_documents: /uploads/files/competition
    app.path.sponsor_images: /uploads/images/sponsor
    app.path.staticPage_documents: /uploads/files/page
    app.path.staticPage_images: /uploads/images/page
    app.path.user_images: /uploads/images/user

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    twig.extension.intl:
        class: Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    twig.extension.sortbyfield:
        class: Snilius\Twig\SortByFieldExtension
        tags:
            - { name: twig.extension }

    app.logout.listener:
        class: App\Listener\LogoutListener

    app.blogPost.listener:
        class: App\Listener\BlogPostListener
        tags:
            - { name: doctrine.orm.entity_listener }
            -
                name: doctrine.orm.entity_listener
                event: preUpdate
                entity: App\Entity\BlogPost
                entity_manager: custom


cocur_slugify:
    lowercase: true
    separator: '-'

ambta_doctrine_encrypt:
    secret_directory_path: '%kernel.project_dir%'   # Default value
    encryptor_class: Defuse # Halite

eu_cookie_law:
    response_injection: true # default true
    template: modules/cookie_modal.html.twig # twig template name, default: EuCookieLawBundle::cookie_law_bar.html.twig

fos_ck_editor:
    default_config: standard
    configs:
        extended:
            toolbar: 'extended_toolbar'
            contentsCss: ['https://use.fontawesome.com/releases/v5.3.1/css/all.css','/assets/css/bootstrap.min.css']
            allowedContent: true
            format_tags: 'p;h3;h4;h5;pre;div'
        standard:
            toolbar: 'standard_toolbar'
            contentsCss: ['https://use.fontawesome.com/releases/v5.3.1/css/all.css','/assets/css/bootstrap.min.css']
            allowedContent: true
            format_tags: 'p;h3;h4;h5;pre;div'
        minimal:
            toolbar: 'minimal_toolbar'
            contentsCss: ['https://use.fontawesome.com/releases/v5.3.1/css/all.css','/assets/css/bootstrap.min.css']
            allowedContent: false 
            format_tags: 'p'
    toolbars:
        configs:
            extended_toolbar: [['Save','Undo','Redo'],['Cut','Copy','Paste','PasteText','RemoveFormat'],['Image','Table','HorizontalRule','SpecialChar'],['Maximize', 'ShowBlocks'],['Source'],'/',['Format'],['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],['NumberedList','BulletedList','-','Outdent','Indent','Blockquote'],['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],['Link','Unlink','Anchor']]
            standard_toolbar: [['Save','Undo','Redo'],['Cut','Copy','Paste','PasteText','RemoveFormat'],['Maximize','ShowBlocks'],['Source'],'/',['Format'],['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],['NumberedList','BulletedList','-','Outdent','Indent','Blockquote'],['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],['Link','Unlink']]
            minimal_toolbar: [['Save','Undo','Redo'],['Cut','Copy','Paste','PasteText','RemoveFormat'],['Source'],'/',['Bold','Italic','Underline','Strike'],['Link','Unlink']]
#    styles:
#        default:
#            - { name: 'Lead', element: 'p', attributes: { class: 'lead'} }
#            - { name: 'Normal', element: 'p' }
